/**
 * argon2id password hashing, computed on the host side with `@noble/hashes`.
 *
 * Not computed in PHP: `password_hash()` is a built-in and cannot be redeclared, so the seam is
 * Drupal's `password` service (`CfwPassword`). The arena is a transient JS allocation (19 MiB at
 * the OWASP floor), measured fine beside a 117 MiB resident wasm. wasm-based argon2 libraries are
 * out because workerd refuses codegen at request time.
 * @module
 */
import { argon2id } from '@noble/hashes/argon2.js';
import { base64ToBytes, bytesToBase64 } from '../db/file-store';
import { ARGON2_FIX_PHP } from '../site/generated/assets';
import { errorMessage } from '../util/errors';

/** the Module key the PHP half resolves through `vrzno_env()` */
export const ARGON2_BRIDGE = 'cfwArgon2';

/**
 * OWASP's floor (m=19456 KiB, t=2, p=1), the settings a hash is written with.
 *
 * Nothing weaker is offered: it would be worse than the bcrypt cost 12 already shipping.
 */
export const ARGON2_DEFAULTS = { m: 19_456, t: 2, p: 1 } as const;

/** the argon2 version byte (0x13, v=19) written into the encoded hash */
export const ARGON2_VERSION = 0x13;

/** what the PHP half sends */
export type Argon2Request = {
	op?: string;
	/** base64 of the UTF-8 password bytes */
	passB64?: string;
	/** base64 of the salt; 16 bytes, generated by the caller */
	saltB64?: string;
	/** KiB of arena */
	m?: number;
	/** passes */
	t?: number;
	/** lanes */
	p?: number;
	/** output length in bytes */
	tagLen?: number;
};

/** a hash tag or the failure text; a failure is a reply, not a throw */
export type Argon2Reply = { ok: true; tagB64: string } | { ok: false; error: string };

/** the ceiling this refuses above, so a bad parameter cannot ask for an arena the isolate lacks */
export const ARGON2_MAX_MEMORY_KIB = 65_536;

/**
 * One hash, decoded (exported so the gate can drive it without a Durable Object).
 *
 * @internal
 */
export function argon2HostCall(req: Argon2Request): Argon2Reply {
	try {
		const m = Number(req.m ?? ARGON2_DEFAULTS.m);
		const t = Number(req.t ?? ARGON2_DEFAULTS.t);
		const p = Number(req.p ?? ARGON2_DEFAULTS.p);
		const tagLen = Number(req.tagLen ?? 32);

		if (!Number.isFinite(m) || m < 8 || m > ARGON2_MAX_MEMORY_KIB) {
			return {
				ok: false,
				error: `memory cost ${String(req.m)} outside 8..${ARGON2_MAX_MEMORY_KIB} KiB`
			};
		}
		if (!Number.isFinite(t) || t < 1 || t > 16)
			return { ok: false, error: `time cost ${String(req.t)}` };
		if (!Number.isFinite(p) || p < 1 || p > 4)
			return { ok: false, error: `lanes ${String(req.p)}` };
		if (!Number.isFinite(tagLen) || tagLen < 16 || tagLen > 64) {
			return { ok: false, error: `tag length ${String(req.tagLen)}` };
		}

		const password = base64ToBytes(String(req.passB64 ?? ''));
		const salt = base64ToBytes(String(req.saltB64 ?? ''));
		if (salt.length < 8) return { ok: false, error: 'salt shorter than 8 bytes' };

		const tag = argon2id(password, salt, { m, t, p, dkLen: tagLen, version: ARGON2_VERSION });
		return { ok: true, tagB64: bytesToBase64(new Uint8Array(tag)) };
	} catch (e) {
		return { ok: false, error: errorMessage(e) };
	}
}

/** the shape `installArgon2` needs of a PHP binary, so it can be driven from a test */
export type Argon2Binary = Record<string, unknown>;

/**
 * Installs the bridge on the PHP Module, masked like the other synchronous bridges (a slice
 * interrupt must not suspend across the long hash frame).
 */
export function installArgon2(binary: Argon2Binary, withMask: <R>(fn: () => R) => R): Argon2Binary {
	binary[ARGON2_BRIDGE] = (json: string) =>
		withMask(() => {
			let req: Argon2Request;
			try {
				req = JSON.parse(json) as Argon2Request;
			} catch (e: any) {
				return JSON.stringify({ ok: false, error: `unparseable request: ${e?.message}` });
			}
			return JSON.stringify(argon2HostCall(req));
		});
	return binary;
}

/**
 * The PHP half: two helpers the sibling module's `CfwPassword` calls.
 *
 * Not a `password_hash()` shim (a built-in, always declared, so a conditional declaration never
 * binds); Drupal's `password` service is the seam.
 *
 * The encoded form is PHP's own (`$argon2id$v=19$m=..,t=..,p=..$salt$tag`, unpadded base64), so a
 * site can migrate off this platform with its passwords still verifying.
 */
export const ARGON2_FIX = ARGON2_FIX_PHP;
