import { argon2id } from '@noble/hashes/argon2.js';
import { base64ToBytes, bytesToBase64 } from '../db/file-store';

/**
 * argon2id password hashing, computed on the HOST side.
 *
 * ## The blocker that was recorded, and the one that is real
 *
 * argon2 was closed on memory: `PHP_PASSWORD_ARGON2_MEMORY_COST` defaults to 64 MiB, the isolate is
 * 128 MB shared between JS and wasm, and an install already peaked at ~115 MiB. That reasoning is
 * correct about ONE mechanism -- an arena inside PHP's own heap, where `memory.grow` has no inverse,
 * so the first hash would raise that object's floor for the rest of its life.
 *
 * It is not correct about argon2id. A JS-side arena is garbage-collected rather than permanent, and
 * OWASP's floor is m=19456 KiB (19 MiB), t=2, p=1 rather than 64 MiB. Measured on a DEPLOYED
 * throwaway (`cfw-arena-probe`, torn down), every OS page touched on both sides:
 *
 * | resident wasm         | transient JS arena     | result |
 * | --------------------- | ---------------------- | ------ |
 * | 96 MiB                | 19 / 32 / 48 / 64 MiB  | all ok |
 * | 117 MiB (auth render) | 19 MiB                 | ok     |
 * | --                    | 19 MiB x 10 in a row   | 10/10  |
 *
 * The first version of that probe touched one byte per 64 KiB wasm page, making 1 OS page in 16
 * resident and understating the footprint 16-fold. These are from the corrected one.
 *
 * ## Why the hash is not computed in PHP
 *
 * Two reasons, and the memory one is the smaller. `password_hash()` is a built-in that cannot be
 * redeclared, so a shim of the kind `curl-fix` and `openssl-fix` use is not available here -- the
 * guard would never pass. Drupal's own seam is the `password` service, which
 * `DrupflareServiceProvider` already alters, so `CfwPassword` in the sibling module calls the
 * helpers below and core's `PhpPassword` never runs. That is an ordinary Drupal service swap rather
 * than a patch, which is what an unmodified module requires.
 *
 * ## Why @noble/hashes rather than an implementation here
 *
 * Audited, dependency-free, synchronous TypeScript. The alternatives lose on this runtime for
 * reasons that are not about quality: `hash-wasm` and `argon2-browser` instantiate their wasm from
 * base64 on first call, which is REQUEST time, and workerd refuses codegen there -- the same rule
 * that forces the interpreter to be instantiated at module scope. A hand-written BlaMka would be
 * ~250 lines of 64-bit arithmetic in a language without a 64-bit integer, to reproduce something
 * already audited.
 */

/** the Module key the PHP half resolves through `vrzno_env()` */
export const ARGON2_BRIDGE = 'cfwArgon2';

/**
 * OWASP's floor, and the settings a hash is written with.
 *
 * m=19456 KiB, t=2, p=1. OWASP lists m=47104/t=1 as the other equal-strength option; that one is
 * 46 MiB and has no reason to be preferred here, where the arena is the scarce thing. Anything
 * BELOW this is not offered -- a weaker argon2 is worse than the bcrypt cost 12 already shipping,
 * which is the objection that closed this item the first time and is still correct at 8 MiB.
 */
export const ARGON2_DEFAULTS = { m: 19_456, t: 2, p: 1 } as const;

/** PHP's own `PASSWORD_ARGON2_*` defaults, for `password_needs_rehash()` parity */
export const ARGON2_VERSION = 0x13;

export type Argon2Request = {
	op?: string;
	/** base64 of the UTF-8 password bytes */
	passB64?: string;
	/** base64 of the salt; 16 bytes, generated by the caller */
	saltB64?: string;
	/** KiB of arena */
	m?: number;
	/** passes */
	t?: number;
	/** lanes */
	p?: number;
	/** output length in bytes */
	tagLen?: number;
};

export type Argon2Reply = { ok: true; tagB64: string } | { ok: false; error: string };

/** the ceiling this refuses above, so a bad parameter cannot ask for an arena the isolate lacks */
export const ARGON2_MAX_MEMORY_KIB = 65_536;

/**
 * One hash, decoded.
 *
 * Exported so the gate can drive it without a Durable Object.
 *
 * @internal
 */
export function argon2HostCall(req: Argon2Request): Argon2Reply {
	try {
		const m = Number(req.m ?? ARGON2_DEFAULTS.m);
		const t = Number(req.t ?? ARGON2_DEFAULTS.t);
		const p = Number(req.p ?? ARGON2_DEFAULTS.p);
		const tagLen = Number(req.tagLen ?? 32);

		if (!Number.isFinite(m) || m < 8 || m > ARGON2_MAX_MEMORY_KIB) {
			return {
				ok: false,
				error: `memory cost ${String(req.m)} outside 8..${ARGON2_MAX_MEMORY_KIB} KiB`
			};
		}
		if (!Number.isFinite(t) || t < 1 || t > 16)
			return { ok: false, error: `time cost ${String(req.t)}` };
		if (!Number.isFinite(p) || p < 1 || p > 4)
			return { ok: false, error: `lanes ${String(req.p)}` };
		if (!Number.isFinite(tagLen) || tagLen < 16 || tagLen > 64) {
			return { ok: false, error: `tag length ${String(req.tagLen)}` };
		}

		const password = base64ToBytes(String(req.passB64 ?? ''));
		const salt = base64ToBytes(String(req.saltB64 ?? ''));
		if (salt.length < 8) return { ok: false, error: 'salt shorter than 8 bytes' };

		const tag = argon2id(password, salt, { m, t, p, dkLen: tagLen, version: ARGON2_VERSION });
		return { ok: true, tagB64: bytesToBase64(new Uint8Array(tag)) };
	} catch (e: any) {
		return { ok: false, error: String(e?.message ?? e) };
	}
}

/** the shape `installArgon2` needs of a PHP binary, so it can be driven from a test */
export type Argon2Binary = Record<string, unknown>;

/**
 * Installs the bridge on the PHP Module.
 *
 * Masked like the other synchronous bridges: an argon2 hash is a long JavaScript frame under the
 * PHP stack, and it is exactly the window a slice interrupt must not suspend across.
 */
export function installArgon2(binary: Argon2Binary, withMask: <R>(fn: () => R) => R): Argon2Binary {
	binary[ARGON2_BRIDGE] = (json: string) =>
		withMask(() => {
			let req: Argon2Request;
			try {
				req = JSON.parse(json) as Argon2Request;
			} catch (e: any) {
				return JSON.stringify({ ok: false, error: `unparseable request: ${e?.message}` });
			}
			return JSON.stringify(argon2HostCall(req));
		});
	return binary;
}

/**
 * The PHP half: two helpers the sibling module's `CfwPassword` calls.
 *
 * NOT a `password_hash()` shim. That function is a built-in and always declared, so a conditional
 * declaration would never bind -- the [[inert-shim-guard]] failure, arrived at from the other
 * direction. Drupal's `password` service is the seam instead.
 *
 * THE ENCODED FORM IS PHP'S OWN, `$argon2id$v=19$m=..,t=..,p=..$salt$tag` with unpadded base64,
 * so a hash written here verifies on any ordinary PHP with ext-argon2 and a site can migrate off
 * this platform without every password becoming unverifiable. That portability is the reason to
 * follow the format rather than invent one.
 */
export const ARGON2_FIX = String.raw`
if (!function_exists('cfw_argon2_available')) {
	$__cfw_argon2 = function_exists('vrzno_env') ? vrzno_env('${ARGON2_BRIDGE}') : null;
	if ($__cfw_argon2 !== null) {
		$GLOBALS['__cfw_argon2'] = $__cfw_argon2;

		function cfw_argon2_available() { return true; }

		/** unpadded base64, which is what PHP's own argon2 encoding uses */
		function cfw_argon2_b64($raw) { return rtrim(base64_encode($raw), '='); }

		function cfw_argon2_raw($password, $salt, $m, $t, $p, $tagLen = 32) {
			$fn = $GLOBALS['__cfw_argon2'];
			$reply = json_decode($fn(json_encode([
				'op' => 'hash',
				'passB64' => base64_encode((string) $password),
				'saltB64' => base64_encode((string) $salt),
				'm' => (int) $m,
				't' => (int) $t,
				'p' => (int) $p,
				'tagLen' => (int) $tagLen,
			])), true);
			if (!is_array($reply) || ($reply['ok'] ?? false) !== true) {
				return null;
			}
			return base64_decode((string) ($reply['tagB64'] ?? ''), true);
		}

		/**
		 * Hashes into PHP's own encoded form.
		 *
		 * @return string|null
		 *   The encoded hash, or NULL when the host refused.
		 */
		function cfw_argon2_hash($password, $m = ${ARGON2_DEFAULTS.m}, $t = ${ARGON2_DEFAULTS.t}, $p = ${ARGON2_DEFAULTS.p}) {
			$salt = random_bytes(16);
			$raw = cfw_argon2_raw($password, $salt, $m, $t, $p);
			if ($raw === null || $raw === false) { return null; }
			return sprintf(
				'$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s',
				${ARGON2_VERSION},
				(int) $m,
				(int) $t,
				(int) $p,
				cfw_argon2_b64($salt),
				cfw_argon2_b64($raw)
			);
		}

		/**
		 * Verifies against an encoded hash, in constant time.
		 *
		 * hash_equals() rather than ===, because a byte-at-a-time comparison of a password digest
		 * is a timing oracle even when the digest itself is memory-hard.
		 */
		function cfw_argon2_verify($password, $encoded) {
			$parts = explode('$', (string) $encoded);
			if (count($parts) !== 6 || $parts[1] !== 'argon2id') { return false; }
			$params = [];
			foreach (explode(',', $parts[3]) as $pair) {
				$kv = explode('=', $pair, 2);
				if (count($kv) === 2) { $params[$kv[0]] = (int) $kv[1]; }
			}
			$salt = base64_decode(strtr($parts[4], '-_', '+/'), false);
			$want = base64_decode(strtr($parts[5], '-_', '+/'), false);
			if ($salt === false || $want === false || $want === '') { return false; }
			$raw = cfw_argon2_raw(
				$password,
				$salt,
				$params['m'] ?? ${ARGON2_DEFAULTS.m},
				$params['t'] ?? ${ARGON2_DEFAULTS.t},
				$params['p'] ?? ${ARGON2_DEFAULTS.p},
				strlen($want)
			);
			if ($raw === null || $raw === false) { return false; }
			return hash_equals($want, $raw);
		}

		/** whether an existing encoded hash was written with weaker parameters than today's */
		function cfw_argon2_needs_rehash($encoded, $m = ${ARGON2_DEFAULTS.m}, $t = ${ARGON2_DEFAULTS.t}, $p = ${ARGON2_DEFAULTS.p}) {
			$parts = explode('$', (string) $encoded);
			if (count($parts) !== 6 || $parts[1] !== 'argon2id') { return true; }
			$params = [];
			foreach (explode(',', $parts[3]) as $pair) {
				$kv = explode('=', $pair, 2);
				if (count($kv) === 2) { $params[$kv[0]] = (int) $kv[1]; }
			}
			return ($params['m'] ?? 0) < (int) $m
				|| ($params['t'] ?? 0) < (int) $t
				|| ($params['p'] ?? 0) !== (int) $p;
		}
	}
}
`;
