/**
 * Reads the Unicode delta table the `drupflare` module ships, and degrades to the polyfill's own
 * answers when it is not mounted.
 *
 * THE DATA IS NOT HERE. It is `../drupflare/src/unicode-tables.php`, packed into
 * `assets/driver.json` by `bun run assets:driver` and written into MEMFS by `mountDriver()` at
 * `src/site-do.ts:1264` -- fifty lines before `MB_FIX` runs, which is what makes a `require` at
 * this point legal.
 *
 * **The reason used to be 4,690 gzipped bytes against a 3 MiB ceiling, and that ceiling is gone.**
 * The placement is unchanged and the surviving reason is better: this is GENERATED data with its own
 * writer (`bun run measure:unicode --write`), and generated data that lives in a `String.raw` block
 * has to be regenerated by hand-editing TypeScript. The asset layer is where the generator can write
 * it. Byte cost is no longer an argument for anything here.
 *
 * Both this and its `MB_FIX` host are INERT on the shipping build, which carries native mbstring --
 * see that file's docblock. They stay for a build that does not.
 *
 * Generated by `bun run measure:unicode --write`, which writes the PHP file and never this one.
 */
export const UNICODE_TABLES = String.raw`
// no eval(): every name here is ours, so nothing collides with an internal function and
// tests/node/php-fragments.spec.ts can lint the body
if (!function_exists('cfw_mb_unicode_data')) {
	/**
	 * The table, or an empty one.
	 *
	 * An empty table is not a failure mode, it is the polyfill unchanged: every lookup misses,
	 * cfw_mb_patch returns its input and both generated patterns come back null, so a site with
	 * no driver pack answers exactly what it answered before the table existed.
	 */
	function cfw_mb_unicode_data() {
		static $d = null;
		if ($d === null) {
			// the harness in scripts/measure/ points this at the sibling checkout; the edge
			// leaves it undefined and takes the mounted path
			$path = defined('CFW_UNICODE_TABLES')
				? CFW_UNICODE_TABLES
				: '/drupal/modules/custom/drupflare/src/unicode-tables.php';
			$d = is_file($path) ? require $path : null;
			if (!is_array($d)) {
				$empty = ['lower' => '', 'upper' => '', 'title' => '', 'fold' => ''];
				$d = [
					'lower' => [], 'upper' => [], 'title' => [], 'fold' => [],
					'leads' => $empty, 'wide' => [], 'titleExtra' => [],
				];
			}
		}
		return $d;
	}

	/**
	 * Pre-maps the codepoints the polyfill would answer wrongly, so its own pass then sees a
	 * character it already agrees with.
	 *
	 * Pre and not post: the polyfill's wrong answer is ambiguous -- three characters share one
	 * stale uppercase -- so a table keyed on its OUTPUT cannot recover the input it came from.
	 * strpbrk first, because a string carrying none of the keys' lead bytes cannot need the strtr.
	 */
	function cfw_mb_patch($s, $which) {
		$d = cfw_mb_unicode_data();
		if ($d['leads'][$which] === '' || strpbrk($s, $d['leads'][$which]) === false) {
			return $s;
		}
		return strtr($s, $d[$which]);
	}

	/** the titlecase of a word-initial character, or null where the polyfill is already right */
	function cfw_mb_title_char($ch) {
		$d = cfw_mb_unicode_data();
		return $d['title'][$ch] ?? null;
	}

	/**
	 * A length-PRESERVING fold, which is what the case-insensitive searches need.
	 *
	 * The polyfill lowercases first, and one codepoint lowercases to two (U+0130 gives i plus a
	 * combining dot), so every index past it shifts and mb_stripos answers an offset into a
	 * string the caller never passed.
	 */
	function cfw_mb_fold_safe($s) {
		$d = cfw_mb_unicode_data();
		if ($d['leads']['fold'] === '' || strpbrk($s, $d['leads']['fold']) === false) {
			return $s;
		}
		return strtr($s, $d['fold']);
	}

	/** east asian width from mbstring's table; null when the pack is absent */
	function cfw_mb_wide_regexp() {
		static $re = false;
		if ($re === false) {
			$w = cfw_mb_unicode_data()['wide'];
			$re = $w === [] ? null : '/[' . implode('', $w) . ']/u';
		}
		return $re;
	}

	function cfw_mb_width($s, $re) {
		$stripped = preg_replace($re, '', $s, -1, $wide);
		return ($wide << 1) +
			\Symfony\Polyfill\Mbstring\Mbstring::mb_strlen((string) $stripped, 'UTF-8');
	}

	/** the class body spliced into the word pattern, empty when the pack is absent */
	function cfw_mb_title_extra() {
		return implode('', cfw_mb_unicode_data()['titleExtra']);
	}
}
`;
