<?php

/**
 * Measures how far the shipping mb_* polyfill is from real mbstring, function by
 * function, so "add the extension" and "fix the polyfill" can be priced against
 * each other instead of argued about.
 *
 * The subject is NOT the wasm build. It is the same PHP the wasm build runs --
 * symfony/polyfill-mbstring layered on symfony/polyfill-iconv, plus this repo's
 * cfw_mb_sanitize -- reproduced in a native process so the oracle (the real
 * extension) is available in the same run. The polyfill is pure PHP, so the
 * reproduction is exact except where the interpreter itself differs: wasm32 has
 * PHP_INT_SIZE 4, and PCRE is a different build. Both are named in the output.
 *
 * The four divergences already on record came from scripts/measure/mb-diff.mjs,
 * which diffs against a LIVE wasm build. This is the wide sweep that one is not;
 * run both, and treat a disagreement between them as this file being wrong.
 *
 * Driven by mb-parity.ts, which generates the sanitiser file out of mb-fix.ts so
 * there is no second copy of it. Run that, not this.
 */

namespace Symfony\Polyfill\Mbstring {
	use Symfony\Polyfill\Iconv\Iconv as IconvPolyfill;

	// Mbstring.php calls iconv_*() unqualified from inside this namespace, so these
	// shadow the extension and force the same two-polyfill stack the edge runs
	function iconv($from, $to, $s)
	{
		return IconvPolyfill::iconv($from, $to, $s);
	}
	function iconv_strlen($s, $encoding = null)
	{
		return IconvPolyfill::iconv_strlen($s, $encoding);
	}
	function iconv_strpos($haystack, $needle, $offset = 0, $encoding = null)
	{
		return IconvPolyfill::iconv_strpos($haystack, $needle, $offset, $encoding);
	}
	// cfw_iconv_strrpos is ICONV_FIX's corrected copy; the generated file omits it
	// under --no-iconv-fix, which is how the fix gets priced
	function iconv_strrpos($haystack, $needle, $encoding = null)
	{
		return function_exists('cfw_iconv_strrpos')
			? \cfw_iconv_strrpos($haystack, $needle, $encoding)
			: IconvPolyfill::iconv_strrpos($haystack, $needle, $encoding);
	}
	function iconv_substr($s, $start, $length = 2147483647, $encoding = null)
	{
		return IconvPolyfill::iconv_substr($s, $start, $length, $encoding);
	}
	function iconv_mime_decode($s, $mode = 0, $encoding = null)
	{
		return IconvPolyfill::iconv_mime_decode($s, $mode, $encoding);
	}
}

namespace {
	use Symfony\Polyfill\Mbstring\Mbstring as P;

	$opt = function (string $name, ?string $default = null) use ($argv): ?string {
		foreach ($argv as $a) {
			if (str_starts_with($a, "--{$name}=")) {
				return substr($a, strlen($name) + 3);
			}
		}
		return $default;
	};

	$root = $opt('root', __DIR__ . '/../../drupal-src');
	$vendor = $root . '/vendor/symfony';
	foreach (['polyfill-iconv/Iconv.php', 'polyfill-mbstring/Mbstring.php'] as $rel) {
		if (!is_file($vendor . '/' . $rel)) {
			fwrite(STDERR, "missing {$vendor}/{$rel}\n");
			exit(2);
		}
		require_once $vendor . '/' . $rel;
	}

	if (!extension_loaded('mbstring')) {
		fwrite(STDERR, "the oracle is the real extension; this php has no mbstring\n");
		exit(2);
	}

	// generated by mb-parity.ts out of mb-fix.ts; defines cfw_mb_sanitize() and
	// CFW_WRAPPED, so the subject is the shipping stack and not a second copy of it
	$sanitize = $opt('sanitize');
	if ($sanitize === null || !is_file($sanitize)) {
		fwrite(STDERR, "run scripts/measure/mb-parity.ts; --sanitize= is generated\n");
		exit(2);
	}
	require_once $sanitize;

	// #region corpus

	$corpus = [
		'ascii' => 'Hello World',
		'ascii_mixed' => 'AbC-123_xyz',
		'latin_accent' => "caf\u{e9} na\u{ef}ve \u{fc}ber",
		'german_sharp_s' => "Stra\u{df}e GRO\u{1e9e}",
		'greek_final' => "\u{39f}\u{394}\u{39f}\u{3a3}",
		'greek_medial' => "\u{3a3}\u{39f}\u{3a6}\u{39f}\u{3a3}",
		'greek_lower' => "\u{3bf}\u{3b4}\u{3cc}\u{3c2}",
		'greek_word_pair' => "\u{39f}\u{394}\u{39f}\u{3a3} \u{39f}\u{394}\u{39f}\u{3a3}",
		'turkish_dotted' => "\u{130}stanbul TITLE",
		'turkish_dotless' => "\u{131}\u{131}k I",
		'cyrillic' => "\u{41f}\u{440}\u{438}\u{432}\u{435}\u{442} \u{41c}\u{438}\u{440}",
		'cjk' => "\u{65e5}\u{672c}\u{8a9e}\u{30c6}\u{30ad}\u{30b9}\u{30c8}",
		'fullwidth' => "\u{ff21}\u{ff22}\u{ff23}\u{ff10}\u{ff11}",
		'halfwidth_kana' => "\u{ff76}\u{ff85}",
		'hangul' => "\u{d55c}\u{ad6d}\u{c5b4}",
		'emoji' => "\u{1f600}\u{1f680}",
		'emoji_zwj' => "\u{1f469}\u{200d}\u{1f4bb}",
		'emoji_skin' => "\u{1f44d}\u{1f3fd}",
		'combining' => "e\u{301}a\u{308}",
		'ligature_fi' => "\u{fb01}sh",
		'armenian_lig' => "\u{587}",
		'lithuanian' => "i\u{307}\u{300}",
		'deseret' => "\u{10400}\u{10401}",
		'cherokee' => "\u{13a0}\u{13a1}",
		'empty' => '',
		'one_char' => 'a',
		'nul_inside' => "ab\0cd",
		'invalid_trunc2' => "abc\xe4\xbddef",
		'invalid_trunc_end' => "abc\xe4\xbd",
		'invalid_surrogate' => "abc\xed\xa0\x80def",
		'invalid_overlong' => "abc\xc0\xafdef",
		'invalid_f5' => "abc\xf5\x80\x80\x80def",
		'invalid_lone_cont' => "abc\x80\x81def",
		'invalid_ff' => "abc\xff\xfedef",
		'latin1_bytes' => "caf\xe9",
	];

	// #endregion

	// #region cases

	/**
	 * Every case is [group, label, args...]; the runner applies the same args to
	 * the extension and to the polyfill and compares the return verbatim.
	 */
	$cases = [];
	$add = function (string $fn, string $label, array $args) use (&$cases) {
		$cases[] = ['fn' => $fn, 'label' => $label, 'args' => $args];
	};

	foreach ($corpus as $name => $s) {
		$add('mb_strtolower', $name, [$s]);
		$add('mb_strtoupper', $name, [$s]);
		$add('mb_strlen', $name, [$s]);
		$add('mb_scrub', $name, [$s]);
		$add('mb_strwidth', $name, [$s]);
		$add('mb_check_encoding', $name, [$s, 'UTF-8']);
		$add('mb_detect_encoding', $name, [$s, ['UTF-8', 'ISO-8859-1'], true]);
		$add('mb_str_split', $name, [$s, 1]);
		$add('mb_str_split', $name . '/n3', [$s, 3]);
		$add('mb_ucfirst', $name, [$s]);
		$add('mb_lcfirst', $name, [$s]);
		$add('mb_trim', $name, [$s]);
		$add('mb_convert_case', $name . '/upper', [$s, MB_CASE_UPPER]);
		$add('mb_convert_case', $name . '/lower', [$s, MB_CASE_LOWER]);
		$add('mb_convert_case', $name . '/title', [$s, MB_CASE_TITLE]);
		$add('mb_convert_encoding', $name . '/utf8', [$s, 'UTF-8', 'UTF-8']);
		$add('mb_convert_encoding', $name . '/8859', [$s, 'ISO-8859-1', 'UTF-8']);
		$add('mb_str_pad', $name, [$s, 12, '.', STR_PAD_BOTH]);
		$add('mb_substr_count', $name, [$s, 'a']);
		$add('mb_strpos', $name, [$s, 'a', 0]);
		$add('mb_stripos', $name, [$s, 'A', 0]);
		$add('mb_strrpos', $name, [$s, 'a', 0]);
		$add('mb_strripos', $name, [$s, 'A', 0]);
		$add('mb_strstr', $name, [$s, 'a', false]);
		$add('mb_stristr', $name, [$s, 'A', true]);
		$add('mb_strrchr', $name, [$s, 'a', false]);
		$add('mb_strrichr', $name, [$s, 'A', false]);
		foreach ([[0, null], [1, 2], [2, null], [-3, null], [0, -1], [1, 1000]] as [$st, $len]) {
			$add('mb_substr', $name . "/{$st}," . var_export($len, true), [$s, $st, $len]);
		}
		$add('mb_ord', $name, [$s]);
		$add('mb_encode_numericentity', $name, [$s, [0x80, 0x10ffff, 0, 0x1fffff], 'UTF-8', false]);
	}

	foreach ([0x41, 0x3a3, 0x1f600, 0xd800, 0x10ffff, 0x110000, -1] as $cp) {
		$add('mb_chr', 'cp' . $cp, [$cp]);
	}

	// #endregion

	// #region run

	$fmt = function ($v) {
		if (is_array($v)) {
			return '[' . implode('|', array_map(fn($x) => bin2hex((string) $x), $v)) . ']';
		}
		if (is_bool($v)) {
			return $v ? 'true' : 'false';
		}
		if ($v === null) {
			return 'null';
		}
		if (is_int($v)) {
			return (string) $v;
		}
		return bin2hex((string) $v);
	};

	$call = function (callable $c, array $args) {
		set_error_handler(fn() => true);
		try {
			$r = $c(...$args);
		} catch (\Throwable $e) {
			$r = 'THROW:' . get_class($e);
		} finally {
			restore_error_handler();
		}
		return $r;
	};

	$results = [];
	foreach ($cases as $c) {
		$fn = $c['fn'];
		if (!function_exists($fn) || !method_exists(P::class, $fn)) {
			continue;
		}
		$sanitized = $c['args'];
		foreach ($sanitized as $i => $a) {
			if (is_string($a)) {
				$sanitized[$i] = cfw_mb_sanitize($a);
			}
		}

		$native = $call($fn, $c['args']);
		$bare = $call([P::class, $fn], $c['args']);
		// the SHIPPING function itself, re-emitted into CfwShip\ by mb-parity.ts. An
		// unwrapped function has no copy there and falls back to the bare polyfill,
		// which is exactly what the edge does for it
		$shipFn = 'CfwShip\\' . $fn;
		$ship = function_exists($shipFn)
			? $call($shipFn, $c['args'])
			: $call([P::class, $fn], $c['args']);
		// what wrapping THIS function too would produce, so "extend the wrapper list"
		// is priced rather than assumed. It is not a free win in both directions:
		// native mb_str_split and mb_lcfirst pass invalid bytes THROUGH, so sanitising
		// them moves a matching case to a divergent one
		$wrapped = $call([P::class, $fn], $sanitized);

		$results[] = [
			'fn' => $fn,
			'label' => $c['label'],
			'native' => $fmt($native),
			'bare' => $fmt($bare),
			'ship' => $fmt($ship),
			'bare_ok' => $fmt($native) === $fmt($bare),
			'ship_ok' => $fmt($native) === $fmt($ship),
			'wrapped_ok' => $fmt($native) === $fmt($wrapped),
		];
	}

	// #endregion

	// #region report

	$byFn = [];
	foreach ($results as $r) {
		$k = $r['fn'];
		$byFn[$k] ??= ['n' => 0, 'bare' => 0, 'ship' => 0, 'wrapped' => 0, 'cases' => []];
		$byFn[$k]['n']++;
		if (!$r['bare_ok']) {
			$byFn[$k]['bare']++;
		}
		if (!$r['wrapped_ok']) {
			$byFn[$k]['wrapped']++;
		}
		if (!$r['ship_ok']) {
			$byFn[$k]['ship']++;
			$byFn[$k]['cases'][] = $r;
		}
	}
	ksort($byFn);

	$totN = array_sum(array_column($byFn, 'n'));
	$totBare = array_sum(array_column($byFn, 'bare'));
	$totShip = array_sum(array_column($byFn, 'ship'));
	$totWrapped = array_sum(array_column($byFn, 'wrapped'));

	// The split that prices the work, asked ONLY of functions that are not wrapped yet.
	// For a wrapped one the question is meaningless -- the wrapper does more than
	// sanitise now, so "what would sanitising alone give" reads as a regression against
	// the real thing rather than as an opportunity.
	$mechanical = 0;
	$genuine = 0;
	$regression = 0;
	foreach ($results as $r) {
		$isWrapped = in_array($r['fn'], CFW_WRAPPED, true);
		if (!$r['ship_ok'] && !$isWrapped && $r['wrapped_ok']) {
			$mechanical++;
		} elseif (!$r['ship_ok']) {
			$genuine++;
		} elseif (!$isWrapped && !$r['wrapped_ok']) {
			$regression++;
		}
	}

	$missing = [];
	foreach (get_extension_funcs('mbstring') as $fn) {
		if (!method_exists(P::class, $fn)) {
			$missing[] = $fn;
		}
	}

	if (in_array('--json', $argv, true)) {
		echo json_encode(
		[
			'php' => PHP_VERSION,
			'cases' => $totN,
			'bare_divergent' => $totBare,
			'ship_divergent' => $totShip,
			'by_function' => $byFn,
			'missing_functions' => $missing,
		],
		JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES,
	),
			"\n";
		exit($totShip === 0 ? 0 : 1);
	}

	echo 'oracle: php ' .
		PHP_VERSION .
		' with mbstring ' .
		(phpversion('mbstring') ?: '?') .
		', PHP_INT_SIZE=' .
		PHP_INT_SIZE .
		"\n";
	echo "subject: symfony/polyfill-mbstring over symfony/polyfill-iconv + cfw_mb_sanitize\n\n";

	echo "| function | cases | bare polyfill | shipping | if wrapped too |\n";
	echo "| --- | --- | --- | --- | --- |\n";
	foreach ($byFn as $fn => $v) {
		// already wrapped, so the last column has no question left to answer -- and a
		// wrapper now does more than sanitise, so answering it anyway reads as a
		// regression against the real function rather than as an opportunity
		if (in_array($fn, CFW_WRAPPED, true)) {
			printf("| %s | %d | %d | %d | wrapped |\n", $fn, $v['n'], $v['bare'], $v['ship']);
			continue;
		}
		$note =
			$v['wrapped'] > $v['ship'] ? ' WORSE' : ($v['wrapped'] < $v['ship'] ? ' better' : '');
		printf(
			"| %s | %d | %d | %d | %d%s |\n",
			$fn,
			$v['n'],
			$v['bare'],
			$v['ship'],
			$v['wrapped'],
			$note,
		);
	}
	printf(
		"| **total** | **%d** | **%d** | **%d** | **%d** |\n\n",
		$totN,
		$totBare,
		$totShip,
		$totWrapped,
	);

	echo "divergent cases still present in the shipping stack:\n\n";
	echo "| function | input | native | shipping |\n";
	echo "| --- | --- | --- | --- |\n";
	foreach ($byFn as $fn => $v) {
		foreach ($v['cases'] as $r) {
			printf(
				"| %s | %s | %s | %s |\n",
				$fn,
				$r['label'],
				substr($r['native'], 0, 48),
				substr($r['ship'], 0, 48),
			);
		}
	}

	printf(
		"\nfunctions the extension has and the polyfill does not: %d\n  %s\n",
		count($missing),
		implode(' ', $missing),
	);
	printf(
		"\n%d of %d cases diverge (%.1f%%); bare polyfill diverges on %d\n",
		$totShip,
		$totN,
		$totN ? (100 * $totShip) / $totN : 0,
		$totBare,
	);
	printf(
		"\nof the %d: %d close by wrapping the function in cfw_mb_sanitize, %d need real work.\n" .
			"wrapping every function indiscriminately would BREAK %d cases that pass today.\n",
		$totShip,
		$mechanical,
		$genuine,
		$regression,
	);

	// #region core exposure

	// which of the divergences Drupal core can actually reach. Counted from the tree
	// rather than listed here, because a frozen list is how a count goes stale
	$callCounts = [];
	foreach (['core/lib', 'core/modules', 'core/includes'] as $sub) {
		$dir = $root . '/' . $sub;
		if (!is_dir($dir)) {
			continue;
		}
		$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
		foreach ($it as $f) {
			if (
				!$f->isFile() ||
				!preg_match('/\.(php|module|inc|install|theme)$/', $f->getFilename())
			) {
				continue;
			}
			if (str_contains($f->getPathname(), '/tests/')) {
				continue;
			}
			if (
				preg_match_all(
					'/\b(mb_[a-z_0-9]+)\s*\(/',
					(string) file_get_contents($f->getPathname()),
					$m,
				)
			) {
				foreach ($m[1] as $name) {
					$callCounts[$name] = ($callCounts[$name] ?? 0) + 1;
				}
			}
		}
	}
	arsort($callCounts);

	if ($callCounts !== []) {
		echo "\ndivergences Drupal core can reach, by call count in the tree:\n\n";
		echo "| function | core call sites | divergent now | after a selective wrap |\n";
		echo "| --- | --- | --- | --- |\n";
		$exposed = 0;
		$exposedAfter = 0;
		foreach ($callCounts as $fn => $n) {
			if (!isset($byFn[$fn])) {
				continue;
			}
			$after = min($byFn[$fn]['ship'], $byFn[$fn]['wrapped']);
			$exposed += $byFn[$fn]['ship'];
			$exposedAfter += $after;
			printf("| %s | %d | %d | %d |\n", $fn, $n, $byFn[$fn]['ship'], $after);
		}
		printf(
			"\ncore's exposure: %d divergent cases now, %d after a selective wrap.\n",
			$exposed,
			$exposedAfter,
		);
	}

	// #endregion

	// #endregion

	exit($totShip === 0 ? 0 : 1);
}
