import { describe, expect, it } from 'vitest';
import { renderPage, type RenderRequest } from '../../src/drupal/site-php';
import { freshSite, inObject, type ServeDo } from '../helpers/serve-do';

/**
 * Which host Drupal builds absolute URLs from, measured on real output rather than on the fragment.
 *
 * `tests/integration/serve-chain.spec.ts` proves the object puts the right origin into the PHP it
 * emits. This proves the other half, which no amount of fragment-matching can: that Symfony and
 * Drupal's URL generator actually use it.
 *
 * IT WAS BROKEN IN A WAY THE FRAGMENTS HID. Every fragment assigned
 * `$_SERVER['HTTP_HOST'] = 'localhost'`, which looks like it sets the host and does not:
 * `Request::create()` builds its OWN server bag from defaults and never reads `$_SERVER`, so the
 * assignment was decorative and the real value came from Symfony's `http://localhost` default. A
 * deployed site therefore sent `http://localhost` in every `Location:` and in the link of every
 * password-reset mail. Passing an ABSOLUTE URI to `Request::create()` is what fixes it.
 *
 * ASSERTED ON `Location:` RATHER THAN ON THE MARKUP, and that is a correction rather than a
 * convenience: Drupal renders links in a page RELATIVELY by design, so there is no absolute URL in
 * the HTML of a core page to check. The redirect target is generated by the same
 * `Url::...->toString()` path that `user_pass_reset_url()` uses, so it is both observable and the
 * mechanism the defect was actually about.
 */

type Payload = Record<string, unknown>;
const REQUEST_TIMEOUT = 900_000;
const ORIGIN = 'https://cfw-origin.example';
const PASS = 'cfw-Origin-Pass-2262';

const render = (site: ServeDo, path: string, request: RenderRequest = {}) =>
	site.runJson(renderPage(path, [], false, request)) as Promise<Payload>;

async function migrated(site: ServeDo): Promise<void> {
	await site.fetch(new Request('https://do.local/__migrate?all=1&prefill=0'));
}

async function claimed(site: ServeDo): Promise<void> {
	await migrated(site);
	await site.fetch(
		new Request('https://do.local/__firstrun', {
			method: 'POST',
			body: JSON.stringify({ adminPass: PASS, siteName: 'Origin' }),
			headers: { 'content-type': 'application/json' }
		})
	);
}

/** the redirect an anonymous visitor gets asking for their own account; needs no credentials */
const anonymousRedirect = (site: ServeDo, origin?: string) =>
	render(site, '/user', origin === undefined ? {} : { origin });

describe("Symfony's own redirect target", () => {
	it(
		'points at the supplied origin',
		async () => {
			const out = await inObject(freshSite(), async (site: ServeDo) => {
				await migrated(site);
				return anonymousRedirect(site, ORIGIN);
			});

			expect(out['error'] ?? null, JSON.stringify(out).slice(0, 300)).toBeNull();
			expect(Number(out['status'])).toBeGreaterThanOrEqual(300);
			expect(Number(out['status'])).toBeLessThan(400);
			expect(String(out['location'])).toContain(ORIGIN);
			expect(String(out['location'])).not.toContain('localhost');
		},
		REQUEST_TIMEOUT
	);

	/**
	 * A CONTROL, and it is not decoration. Without it, a render that produced no absolute URL at all
	 * would satisfy every "does not say localhost" assertion here and read as a fix.
	 */
	it(
		'still says localhost when no origin is supplied',
		async () => {
			const out = await inObject(freshSite(), async (site: ServeDo) => {
				await migrated(site);
				return anonymousRedirect(site);
			});

			expect(String(out['location'])).toContain('http://localhost/');
			expect(String(out['location'])).not.toContain(ORIGIN);
		},
		REQUEST_TIMEOUT
	);

	// a non-default port is part of the host, and dropping it breaks every link on `wrangler dev`
	it(
		'keeps a non-default port',
		async () => {
			const out = await inObject(freshSite(), async (site: ServeDo) => {
				await migrated(site);
				return anonymousRedirect(site, 'http://localhost:8787');
			});

			expect(String(out['location'])).toContain('http://localhost:8787/');
		},
		REQUEST_TIMEOUT
	);
});

/**
 * Drupal's OWN generator, which is the half that matters for mail.
 *
 * The login redirect is built by `Url::fromRoute(...)` rather than by Symfony, and it is the same
 * call `user_pass_reset_url()` makes -- so a reset link mailed to a user and this `Location:` are
 * wrong or right together. That is the concrete harm behind "renders against localhost": a user
 * clicks the link in their mail and their own browser tries to open their own machine.
 */
describe("Drupal's URL generator", () => {
	it(
		'builds the post-login redirect from the supplied origin',
		async () => {
			const location = await inObject(freshSite(), async (site: ServeDo) => {
				await claimed(site);
				const out = await render(site, '/user/login', {
					origin: ORIGIN,
					method: 'POST',
					body: `name=admin&pass=${encodeURIComponent(PASS)}&form_id=user_login_form&op=Log+in`,
					contentType: 'application/x-www-form-urlencoded'
				});
				expect(Number(out['status']), JSON.stringify(out).slice(0, 300)).toBe(303);
				return String(out['location']);
			});

			expect(location).toContain(`${ORIGIN}/user/1`);
			expect(location).not.toContain('localhost');
		},
		REQUEST_TIMEOUT
	);
});
