/**
 * Emits the edge-readable TypeScript for everything declared in `config/`.
 *
 *   bun run gen:config          rewrite the generated modules
 *   bun run gen:config --check  fail if what is on disk disagrees
 *
 * THE WORKER CANNOT READ YAML AT RUNTIME. There is no filesystem in a Worker, so a declaration that
 * has to reach the edge is compiled into the bundle or it does not exist. That is the whole reason
 * this generator exists rather than a loader, and it is the same pattern `src/ops/shipped-lock.ts`
 * and `src/ops/driver-digest.ts` already follow.
 *
 * `composer.lock` stays authoritative for VERSIONS. `config/modules.yml` says which modules the
 * project has an opinion about and what that opinion is; it never names a version.
 *
 * `tests/node/config-generated.spec.ts` runs this in `--check` mode, so an edit to the YAML that was
 * not regenerated fails the gate rather than shipping a stale constant.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parse } from 'yaml';

const ROOT = resolve(import.meta.dirname, '..');
const SOURCE = resolve(ROOT, 'config', 'modules.yml');
const TARGET = resolve(ROOT, 'src', 'ops', 'generated', 'modules.ts');
const QUOTAS_SOURCE = resolve(ROOT, 'config', 'quotas.yml');
const QUOTAS_TARGET = resolve(ROOT, 'scripts', 'generated', 'quotas.ts');

export type ModuleDecl = {
	needs?: string[];
	why?: string;
	lift?: string;
	vectors?: string[];
	verified?: string;
	capabilityEvidence?: string;
	shipping?: boolean;
};

export type ModulesConfig = {
	cron: { known: string[]; policy: Record<string, { run: boolean; reason?: string }> };
	modules: Record<string, ModuleDecl>;
};

export function readModulesConfig(path = SOURCE): ModulesConfig {
	const doc = parse(readFileSync(path, 'utf8')) as ModulesConfig;
	if (!doc?.modules) throw new Error(`${path} declares no modules`);
	if (!doc.cron?.policy) throw new Error(`${path} declares no cron policy`);

	// a cron hook the ring is told to run but that is not in the discovered fallback list would be
	// scheduled against a site that has no such implementation; the two are one declaration
	for (const name of Object.keys(doc.cron.policy)) {
		if (!doc.cron.known.includes(name)) {
			throw new Error(`cron.policy names ${name}, which cron.known does not list`);
		}
	}
	return doc;
}

const lit = (s: string) => JSON.stringify(s);

export function renderModules(config: ModulesConfig): string {
	const names = Object.keys(config.modules).sort();

	const tier: string[] = [];
	const verified: string[] = [];
	const evidence: string[] = [];
	const shipping: string[] = [];

	for (const name of names) {
		const m = config.modules[name] as ModuleDecl;
		if (m.why !== undefined) {
			const parts = [`needs: [${(m.needs ?? []).map(lit).join(', ')}]`, `why: ${lit(m.why)}`];
			if (m.lift) parts.push(`lift: ${lit(m.lift)}`);
			if (m.vectors) parts.push(`vectors: [${m.vectors.map(lit).join(', ')}]`);
			tier.push(`\t${lit(name)}: { ${parts.join(', ')} }`);
		}
		if (m.verified) verified.push(`\t${lit(name)}: ${lit(m.verified)}`);
		if (m.capabilityEvidence) evidence.push(`\t${lit(name)}: ${lit(m.capabilityEvidence)}`);
		if (m.shipping) shipping.push(`\t${lit(name)}`);
	}

	const cron = Object.entries(config.cron.policy).map(([name, p]) => {
		const body = p.reason ? `run: ${p.run}, reason: ${lit(p.reason)}` : `run: ${p.run}`;
		return `\t${lit(name)}: { ${body} }`;
	});

	return `// GENERATED by scripts/gen-config.ts from config/modules.yml. Do not edit.

import type { ModuleCapability } from '../catalog.js';
import type { CronHookPolicy } from '../cron.js';
import type { TierNote } from '../module-tiers.js';

export const GENERATED_TIER_NOTES: Readonly<Record<string, TierNote>> = {
${tier.join(',\n')}
};

export const GENERATED_VERIFIED: Readonly<Record<string, string>> = {
${verified.join(',\n')}
};

export const GENERATED_CAPABILITY_EVIDENCE: Readonly<Record<string, string>> = {
${evidence.join(',\n')}
};

export const GENERATED_SHIPPING_CONTRIB: readonly string[] = [
${shipping.join(',\n')}
];

export const GENERATED_CRON_KNOWN: readonly string[] = [
${config.cron.known.map((n) => `\t${lit(n)}`).join(',\n')}
];

export const GENERATED_CRON_POLICY: Record<string, CronHookPolicy> = {
${cron.join(',\n')}
};

/** every capability named anywhere in the declaration, so a typo cannot pass as a new capability */
export const GENERATED_CAPABILITIES: readonly ModuleCapability[] = [
${[...new Set(names.flatMap((n) => config.modules[n]?.needs ?? []))]
	.sort()
	.map((c) => `\t${lit(c)} as ModuleCapability`)
	.join(',\n')}
];
`;
}

export type QuotaDecl = { value: number; why?: string };

export function readQuotasConfig(path = QUOTAS_SOURCE): Record<string, QuotaDecl> {
	const doc = parse(readFileSync(path, 'utf8')) as { free?: Record<string, QuotaDecl> };
	if (!doc?.free) throw new Error(`${path} declares no free quotas`);
	for (const [key, entry] of Object.entries(doc.free)) {
		if (typeof entry?.value !== 'number' || !Number.isFinite(entry.value)) {
			throw new Error(`quotas.free.${key} has no numeric value`);
		}
	}
	return doc.free;
}

/**
 * The quota constants, emitted with a literal type per field.
 *
 * UNDER `scripts/generated/` RATHER THAN `src/`, and the reachability scan is what settled it: only
 * `scripts/measure/free-envelope.ts` reads these, so a copy under `src/ops/generated/` was an
 * off-edge module. The four `src/` mentions of `FREE_QUOTAS` are all docblocks, and they scored as
 * callers until the scan stopped counting comments. A generated file belongs beside its consumer.
 */
export function renderQuotas(free: Record<string, QuotaDecl>): string {
	const rows = Object.entries(free).map(([key, entry]) => {
		const why = entry.why ? `\t/** ${entry.why.replace(/\s+/g, ' ')} */\n` : '';
		return `${why}\t${key}: ${entry.value}`;
	});
	return `// GENERATED by scripts/gen-config.ts from config/quotas.yml. Do not edit.

/**
 * Cloudflare's free-plan meters, as declared rather than as remembered.
 *
 * Every entry carries the reason it is that number, because several were wrong once and read as
 * platform facts while they were guesses. rowsPerAlarmArm came from the published "a setAlarm() is
 * one row written", which is true about the setAlarm and false about the firing.
 */
export const GENERATED_FREE_QUOTAS = {
${rows.join(',\n')}
} as const;
`;
}

if (import.meta.main) {
	const check = process.argv.includes('--check');
	const outputs = [
		{
			target: TARGET,
			source: 'config/modules.yml',
			rendered: renderModules(readModulesConfig())
		},
		{
			target: QUOTAS_TARGET,
			source: 'config/quotas.yml',
			rendered: renderQuotas(readQuotasConfig())
		}
	];

	const read = (path: string): string | null => {
		try {
			return readFileSync(path, 'utf8');
		} catch {
			return null;
		}
	};

	if (check) {
		const stale = outputs.filter((o) => read(o.target) !== o.rendered);
		if (stale.length === 0) {
			console.log('gen:config: every generated module agrees with config/');
			process.exit(0);
		}
		for (const o of stale)
			console.error(`gen:config: ${o.target} is STALE against ${o.source}.`);
		console.error('  run `bun run gen:config` and commit the result.');
		process.exit(1);
	}

	for (const o of outputs) writeFileSync(o.target, o.rendered);
	const config = readModulesConfig();
	console.log(
		`gen:config: ${Object.keys(config.modules).length} modules, ` +
			`${Object.keys(config.cron.policy).length} cron policies, ` +
			`${Object.keys(readQuotasConfig()).length} quotas -> src/ops/generated/, scripts/generated/`
	);
}
