/**
 * Packs the PHP, HTML, CSS, JS and YAML files under `src/site/` into `src/site/generated/assets.ts`.
 *
 *   bun run gen:assets          rewrite the generated module
 *   bun run gen:assets --check  fail if what is on disk disagrees
 *
 * A Worker has no filesystem, so each file becomes one exported string constant. The name is the
 * path under its kind's directory with `/` and `-` turned into `_`, upper-cased, plus the kind:
 * `php/mb/sanitize.php` is `MB_SANITIZE_PHP`, and `php/host-helpers.php` is `HOST_HELPERS_PHP`. Two
 * files that map to one name fail the run. Every `.php` file opens with a `<?php` line so editors and
 * `php -l` treat it as PHP; that line is dropped from the constant, and a consumer that runs the text
 * as a whole script puts it back.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const SOURCE = resolve(ROOT, 'src', 'site');
const TARGET = resolve(ROOT, 'src', 'site', 'generated', 'assets.ts');

const KINDS = ['php', 'html', 'css', 'js', 'yaml'] as const;
const PHP_TAG = '<?php\n';

export type Asset = { name: string; text: string };

/** `mb/sanitize.php` -> `MB_SANITIZE_PHP` */
export function constantName(file: string, kind: string): string {
	const stem = file.replace(new RegExp(`\\.${kind}$`), '');
	return `${stem.replace(/[/-]/g, '_').toUpperCase()}_${kind.toUpperCase()}`;
}

/** the string a consumer gets for one file */
export function assetText(file: string, raw: string): string {
	if (!file.endsWith('.php')) return raw;
	if (!raw.startsWith(PHP_TAG)) throw new Error(`${file} must open with a <?php line`);
	return raw.slice(PHP_TAG.length);
}

export function readAssets(root = SOURCE): Asset[] {
	const assets: Asset[] = [];
	const owner = new Map<string, string>();
	for (const kind of KINDS) {
		let files: string[];
		try {
			files = readdirSync(resolve(root, kind), { recursive: true, encoding: 'utf8' })
				.map((f) => f.split('\\').join('/'))
				.filter((f) => f.endsWith(`.${kind}`));
		} catch {
			continue;
		}
		for (const file of files.sort()) {
			const name = constantName(file, kind);
			const clash = owner.get(name);
			if (clash !== undefined) {
				throw new Error(`${kind}/${file} and ${clash} are both ${name}`);
			}
			owner.set(name, `${kind}/${file}`);
			const raw = readFileSync(resolve(root, kind, file), 'utf8');
			assets.push({ name, text: assetText(file, raw) });
		}
	}
	return assets.sort((a, b) => (a.name < b.name ? -1 : 1));
}

export function renderAssets(assets: Asset[]): string {
	const body = assets
		.map((a) => `export const ${a.name} = ${JSON.stringify(a.text)};\n`)
		.join('\n');
	return `// GENERATED by scripts/gen-assets.ts from src/site/php, html, css, js and yaml. Do not edit.\n\n${body}`;
}

if (import.meta.main) {
	const rendered = renderAssets(readAssets());
	if (process.argv.includes('--check')) {
		let current = '';
		try {
			current = readFileSync(TARGET, 'utf8');
		} catch {
			// a missing file is drift like any other
		}
		if (current === rendered) {
			console.log('gen-assets: src/site/generated/assets.ts is current');
			process.exit(0);
		}
		console.error(
			'gen-assets: src/site/generated/assets.ts is stale; run `bun run gen:assets`'
		);
		process.exit(1);
	}
	writeFileSync(TARGET, rendered);
	console.log(`gen-assets: wrote ${TARGET}`);
}
