/**
 * The layer path for one opcache cache file, or null for one that must not ship.
 *
 * `/tmp/<id>/drupal/core/x.php.bin` becomes `.opcache/<id>/drupal/core/x.php.bin`, which the mount
 * places at `/drupal/.opcache/...` and `/tmp/<id>` is then linked to. Nothing under `sites/` ships:
 * `settings.php` compiles with the baking site's `hash_salt` in it, and the layer is a public asset.
 */
export function layerPath(path: string): string | null {
	const m = /^\/tmp\/([0-9a-f]{32})\/drupal\/(.+\.bin)$/.exec(path);
	if (!m) return null;
	const [, id, rest] = m as unknown as [string, string, string];
	if (rest.startsWith('sites/')) return null;
	return `.opcache/${id}/drupal/${rest}`;
}

/** the one system id every layer path carries, refusing a mixture */
export function systemIdOf(paths: readonly string[]): string {
	const ids = new Set(paths.map((p) => p.split('/')[1]).filter((s): s is string => Boolean(s)));
	if (ids.size !== 1) throw new Error(`expected one system id, found ${[...ids].join(', ')}`);
	return [...ids][0] as string;
}

/** the exact bytes that belong in src/ops/opcache-pack.ts */
export function serialiseOpcachePack(
	pack: { systemId: string; files: number; bytes: number; source: string } | null
): string {
	return `/**
 * The opcache file cache the pack ships. GENERATED by \`scripts/bake-opcache.ts\`; null when none was
 * baked, in which case the \`pack\` arm mounts nothing and compiles as \`off\` would.
 *
 * \`systemId\` is the directory opcache keys the cache by. It is derived from the interpreter build, so
 * a cache baked on another binary is never read, and the mount has to know it to link \`/tmp\` to it.
 * \`source\` is \`opcacheSourceKey()\` at bake time; the mount skips a cache compiled from other sources.
 */
export const OPCACHE_PACK: {
	systemId: string;
	files: number;
	bytes: number;
	source: string;
} | null = ${
		pack === null
			? 'null'
			: `{\n\tsystemId: '${pack.systemId}',\n\tfiles: ${pack.files},\n\tbytes: ${pack.bytes},\n\tsource: '${pack.source}'\n}`
	};
`;
}
