/**
 * Builds the release payload: every generated byte a clean checkout needs before `wrangler deploy`.
 *
 * ```sh
 * bun scripts/release-payload.ts                 # build dist/drupflare-worker-<version>.tar.gz
 * bun scripts/release-payload.ts --check-bundle   # dry-run the canonical config, price the bundle
 * ```
 *
 * WHY A PAYLOAD AND NOT A BUILD. `assets/` is 97 MB of generated packs and `.interp/` holds the
 * interpreter; both are gitignored, so a clean checkout cannot deploy. Regenerating them needs native
 * PHP with a Drupal kernel, Docker, `node:sqlite`, a 97 MB Drupal tarball and a cross-repo token for
 * phasm's artifacts -- and the interpreter artifact MOVES between phasm builds (12,218,400 then
 * 12,218,393 bytes for the same rc), so "rebuild it in CI" would not pin the bytes anyway. The payload
 * pins them by sha256 and needs neither Docker nor a token to consume.
 *
 * The shipping set is DERIVED from `assets/.assetsignore` rather than listed here, and the interpreter
 * files are derived from the alias in `wrangler.jsonc`. Both derivations are asserted, so a change to
 * either file that this script cannot carry fails the build instead of shipping a short payload.
 *
 * @see scripts/hydrate.ts for the consuming half
 * @see PUBLISHING.md for the release flow this is step one of
 */

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
	existsSync,
	mkdirSync,
	readFileSync,
	readdirSync,
	rmSync,
	statSync,
	writeFileSync
} from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { FREE_CEILING, measureBundle } from './measure/bundle-size';
import { decodeLatin1, readEntry, readPack } from './scrub-pack-secrets';

/** the only two directories a payload may write into; `vendor/` is deliberately not one of them */
export const PAYLOAD_ROOTS = ['assets/', '.interp/'] as const;

/** one entry of the payload plan: a single file, or every file under a directory */
export type PlanEntry = { readonly path: string; readonly dir?: boolean };

/**
 * The asset half of the payload, declared rather than re-derived.
 *
 * Implementing gitignore semantics against `.assetsignore` would be a second implementation of the
 * matcher wrangler already runs. `assertCoversAssetsIgnore()` compares this list to that file in both
 * directions instead, so the two cannot drift without failing.
 */
export const PAYLOAD_ASSETS: readonly PlanEntry[] = [
	{ path: 'assets/driver.json' },
	{ path: 'assets/prefill.json' },
	{ path: 'assets/drupal-pf/core.pf.json' },
	{ path: 'assets/drupal-pf/core.pf.bin' },
	{ path: 'assets/drupal-sql', dir: true }
];

/**
 * Build records the gate reads and the edge never serves.
 *
 * `tests/node/twig-bake.spec.ts` asserts the compiled Twig cache against this manifest, and it is the
 * only thing that catches a repack without a bake -- 26 compiled templates shipped under a prefix the
 * runtime never asks for, which renders a byte-identical page. Carrying 7.8 KB is what lets the
 * release lane run that spec; `.assetsignore` still withholds it from the edge, because everything
 * under `assets/drupal/` is re-ignored.
 */
export const PAYLOAD_RECORDS: readonly PlanEntry[] = [{ path: 'assets/drupal/twig-bake.json' }];

/** a payload file, content-addressed */
export type PayloadFile = { path: string; bytes: number; sha256: string };

/** what `manifest.json` inside the tarball carries */
export type PayloadManifest = {
	name: string;
	version: number;
	release: string;
	commit: string;
	interpreter: string[];
	files: PayloadFile[];
	totals: { files: number; bytes: number };
};

/** JSONC: strip line comments, the same way `tests/node/wrangler-reachability.spec.ts` does */
export function readJsonc(path: string): Record<string, unknown> {
	const raw = readFileSync(path, 'utf8');
	const stripped = raw
		.split('\n')
		.map((line) => line.replace(/^\s*\/\/.*$/, ''))
		.join('\n');
	return JSON.parse(stripped) as Record<string, unknown>;
}

/** every `!`-negated path in an `.assetsignore`, in file order */
export function negatedPaths(ignoreSource: string): string[] {
	return rules(ignoreSource)
		.filter((line) => line.startsWith('!'))
		.map((line) => line.slice(1));
}

/** the ignore file's rules, comments and blanks dropped */
function rules(ignoreSource: string): string[] {
	return ignoreSource
		.split('\n')
		.map((line) => line.trim())
		.filter((line) => line !== '' && !line.startsWith('#'));
}

/**
 * The paths an `.assetsignore` actually ships, which is not the same as its negations.
 *
 * `!/drupal-pf/` followed by `/drupal-pf/*` is the gitignore idiom for reaching INTO a directory
 * without shipping it: the negation makes the directory traversable and the next line re-ignores its
 * contents, so what ships is the two explicit negations after it. Counting the directory as a shipped
 * path would demand the payload carry the whole 13 MB of it.
 */
export function shippedPaths(ignoreSource: string): string[] {
	const lines = rules(ignoreSource);
	const reIgnored = new Set(lines.filter((l) => !l.startsWith('!')));
	return negatedPaths(ignoreSource)
		.filter((path) => !(path.endsWith('/') && reIgnored.has(`${path}*`)))
		.map((path) => (path.endsWith('/') ? path.slice(0, -1) : path));
}

/**
 * Asserts the declared asset plan and `.assetsignore` describe the same set.
 *
 * Bidirectional on purpose: a file added to the ignore file but not here would ship to the edge and be
 * missing from the payload, and one added here but not there would be carried and never uploaded.
 *
 * @throws when either side names something the other does not.
 */
export function assertCoversAssetsIgnore(
	ignoreSource: string,
	plan: readonly PlanEntry[] = PAYLOAD_ASSETS
): void {
	const declared = new Set(plan.map((e) => '/' + relative('assets', e.path)));
	const shipped = shippedPaths(ignoreSource);

	const missing = shipped.filter((p) => !declared.has(p));
	const extra = [...declared].filter((p) => !shipped.includes(p));
	if (missing.length || extra.length) {
		throw new Error(
			'the payload plan and assets/.assetsignore disagree:\n' +
				missing
					.map((p) => `  ${p} ships to the edge and is not in the payload`)
					.join('\n') +
				(missing.length && extra.length ? '\n' : '') +
				extra.map((p) => `  ${p} is in the payload and is not served`).join('\n') +
				'\nUpdate PAYLOAD_ASSETS in scripts/release-payload.ts to match.'
		);
	}
}

/**
 * The interpreter files the canonical config's binary seam imports.
 *
 * Read out of the seam rather than hardcoded because the seam has already moved once: 8.3 out of
 * `vendor/` to 8.5 out of `.interp/`. A hardcoded list would have shipped the wrong binary and the
 * dry-run would still have passed on this machine, where both exist.
 *
 * @throws when the seam imports from `vendor/`, which holds hand-built binaries that exist on one
 *   machine and cannot be carried by a payload at all.
 */
export function interpreterFiles(root: string): string[] {
	const config = readJsonc(join(root, 'wrangler.jsonc'));
	const alias = (config.alias ?? {}) as Record<string, string>;
	const seam = Object.values(alias).find((target) => target.includes('php-binary'));
	if (!seam) {
		throw new Error(
			'wrangler.jsonc has no php-binary alias, so which interpreter ships is undecided'
		);
	}
	const seamPath = resolve(root, seam);
	const source = readFileSync(seamPath, 'utf8');

	const specifiers = [...source.matchAll(/from\s+'([^']+)'/g)]
		.map((m) => m[1])
		.filter((s): s is string => s !== undefined);
	const fromVendor = specifiers.filter((s) => s.includes('vendor/'));
	if (fromVendor.length) {
		throw new Error(
			`${seam} imports ${fromVendor.join(', ')} from vendor/, which holds hand-built ` +
				'binaries that exist on one machine. A payload cannot carry them, so the ' +
				'canonical config cannot be deployed from a clean checkout. Point the alias at a ' +
				'seam whose imports all resolve under .interp/.'
		);
	}
	return specifiers
		.filter((s) => s.includes('.interp/'))
		.map((s) => relative(root, resolve(seamPath, '..', s)))
		.sort();
}

/** the whole payload plan for a checkout: shipped assets, build records, and the aliased interpreter */
export function payloadPlan(root: string): {
	assets: readonly PlanEntry[];
	records: readonly PlanEntry[];
	interpreter: string[];
} {
	const ignoreSource = readFileSync(join(root, 'assets/.assetsignore'), 'utf8');
	assertCoversAssetsIgnore(ignoreSource);

	// a record that the edge serves is a disclosure, not a record
	const shipped = new Set(shippedPaths(ignoreSource));
	for (const record of PAYLOAD_RECORDS) {
		const served = '/' + relative('assets', record.path);
		if (shipped.has(served)) {
			throw new Error(`${record.path} is a build record and .assetsignore serves it`);
		}
	}
	return {
		assets: PAYLOAD_ASSETS,
		records: PAYLOAD_RECORDS,
		interpreter: interpreterFiles(root)
	};
}

/** every file under `dir`, repo-relative and sorted, so a payload's order is stable */
function walk(root: string, dir: string): string[] {
	const out: string[] = [];
	for (const entry of readdirSync(join(root, dir), { withFileTypes: true }).sort((a, b) =>
		a.name < b.name ? -1 : 1
	)) {
		const rel = join(dir, entry.name);
		if (entry.isDirectory()) out.push(...walk(root, rel));
		else out.push(rel);
	}
	return out;
}

/**
 * Expands a plan to the files on disk.
 *
 * @throws naming every missing path and the command that produces it, because "the payload is 3 files
 *   short" is the failure this whole pipeline exists to make loud.
 */
export function expandPlan(root: string, plan: ReturnType<typeof payloadPlan>): string[] {
	const out: string[] = [];
	const missing: string[] = [];

	for (const entry of [...plan.assets, ...plan.records]) {
		const abs = join(root, entry.path);
		if (!existsSync(abs)) {
			missing.push(entry.path);
			continue;
		}
		if (entry.dir) out.push(...walk(root, entry.path));
		else out.push(entry.path);
	}
	for (const file of plan.interpreter) {
		if (existsSync(join(root, file))) out.push(file);
		else missing.push(file);
	}

	if (missing.length) {
		throw new Error(
			`the payload is incomplete; ${missing.length} path(s) are not built:\n` +
				missing
					.map((p) => `  ${p} <- ${PRODUCED_BY[producerKey(p)] ?? 'unknown'}`)
					.join('\n')
		);
	}
	return out;
}

/** which command produces each payload path, keyed by the directory that identifies it */
const PRODUCED_BY: Record<string, string> = {
	'assets/driver.json': 'bun run assets:driver',
	'assets/prefill.json': 'bun scripts/lift-prefill.ts (needs a running worker)',
	'assets/drupal/twig-bake.json': 'bun run assets:twig',
	'assets/drupal-pf': 'bun run assets:twig && bun run assets:core && bun run assets:pack',
	'assets/drupal-sql': 'bun run assets:sql (needs assets/drupal/site.sqlite)',
	'.interp': 'bun run build:wasm (needs docker and gh auth to drupflare/phasm)'
};

function producerKey(path: string): string {
	if (PRODUCED_BY[path]) return path;
	for (const depth of [2, 1]) {
		const dir = path.split('/').slice(0, depth).join('/');
		if (PRODUCED_BY[dir]) return dir;
	}
	return path;
}

/** sha256 of a file, lowercase hex */
export function sha256(path: string): string {
	return createHash('sha256').update(readFileSync(path)).digest('hex');
}

/** Builds the manifest for a file list. No timestamp: the same inputs describe the same payload. */
export function buildManifest(
	root: string,
	release: string,
	commit: string,
	files: string[],
	interpreter: string[]
): PayloadManifest {
	const entries = files.map((path) => ({
		path,
		bytes: statSync(join(root, path)).size,
		sha256: sha256(join(root, path))
	}));
	return {
		name: 'drupflare-worker-payload',
		version: 1,
		release,
		commit,
		interpreter,
		files: entries,
		totals: {
			files: entries.length,
			bytes: entries.reduce((n, e) => n + e.bytes, 0)
		}
	};
}

/** a credential found in bytes the payload would publish */
export type SeededCredential = { path: string; kind: string };

/**
 * Patterns whose presence in a shipped asset means every deployed site shares one secret.
 *
 * Workers assets are served publicly, so `/drupal-sql/0064.json` is fetchable by anyone, and the
 * chunks are the database. A one-click deploy that seeds the same admin hash and the same
 * `system.private_key` into every site is a worse posture than no admin account.
 *
 * EVERY PATTERN MATCHES A VALUE, NEVER AN IDENTIFIER, and that is what lets this scan the Drupal
 * tree at all. Measured over the 11,444 files in `core.pf.bin`: bare `hash_salt` hits 11 files
 * (`default.settings.php`, `rebuild.php`, the token calculator) and bare `system.private_key` hits
 * `PrivateKey.php`. Value-shaped patterns hit none of them, and still catch the real rows. An
 * identifier scan over this file set would fire on every release forever, which is the same as not
 * having a gate.
 */
const CREDENTIAL_PATTERNS: readonly { kind: string; re: RegExp }[] = [
	// a whole crypt string, not a prefix: `$2y$12$` plus the 53 characters of salt and digest
	{ kind: 'bcrypt password hash', re: /\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}/ },
	// the serialized state row, not the class that reads it
	{ kind: 'system.private_key', re: /system\.private_key[\s\S]{0,120}s:\d{2,}:/ },
	// an assignment of a NON-EMPTY literal; the scrubbed pack assigns '' and passes
	{ kind: 'hash salt', re: /\$settings\['hash_salt'\]\s*=\s*'[^']+'/ }
];

/** Applies every pattern to one body of text. */
function matchCredentials(path: string, body: string): SeededCredential[] {
	return CREDENTIAL_PATTERNS.filter(({ re }) => re.test(body)).map(({ kind }) => ({
		path,
		kind
	}));
}

/**
 * Scans payload files for seeded credentials, INCLUDING inside the per-file packs.
 *
 * The earlier version skipped anything that was not `.json`, which meant it never opened
 * `core.pf.bin` -- the 12 MB blob holding `settings.php`. So its `hash_salt` pattern had no file to
 * fire on and the gate reported clean while the payload published a real salt. A scanner that
 * cannot reach the bytes it has a pattern for is not a gate.
 */
export function scanSeededCredentials(root: string, files: string[]): SeededCredential[] {
	const found: SeededCredential[] = [];
	for (const path of files) {
		if (/\.pf\.bin$/.test(path)) {
			found.push(...scanPerFilePack(root, path));
			continue;
		}
		// the pf index carries paths and offsets, never content, so scanning it is noise
		if (/\.pf\.json$/.test(path) || !/\.json$/.test(path)) continue;
		found.push(...matchCredentials(path, readFileSync(join(root, path), 'utf8')));
	}
	return found;
}

/** Decompresses every member of a per-file pack and scans it, naming the member that matched. */
function scanPerFilePack(root: string, binPath: string): SeededCredential[] {
	const dir = join(root, binPath.replace(/\/[^/]+$/, ''));
	if (!existsSync(join(dir, 'core.pf.json'))) return [];
	const { index, bin } = readPack(dir);
	const found: SeededCredential[] = [];
	for (const entry of Object.values(index)) {
		found.push(
			...matchCredentials(`${binPath}:${entry.p}`, decodeLatin1(readEntry(bin, entry)))
		);
	}
	return found;
}

/**
 * Reads the gzipped bundle size out of wrangler's own output.
 *
 * Wrangler prints KiB (`gzip: 2808.67 KiB`) and the ceiling is in bytes, so the conversion is the
 * whole point of this function. The report has already quoted one such figure as bytes, which
 * overstated the headroom by 67,406.
 *
 * @returns bytes, or `undefined` when the line is absent.
 */
export function parseWranglerGzipBytes(stdout: string): number | undefined {
	const kib = stdout.match(/gzip:\s*([\d.]+)\s*KiB/)?.[1];
	if (kib !== undefined) return Math.round(parseFloat(kib) * 1024);
	const mib = stdout.match(/gzip:\s*([\d.]+)\s*MiB/)?.[1];
	if (mib !== undefined) return Math.round(parseFloat(mib) * 1024 * 1024);
	return undefined;
}

/**
 * How a measured bundle sits against the free ceiling.
 *
 * Same arithmetic `measureBundle()` does over an outdir, applied to the figure wrangler PRINTS --
 * which that instrument's own docblock names as the number to quote, because concatenation order and
 * the zlib version move the local one.
 */
export function ceilingVerdict(bytes: number): { fits: boolean; headroom: number } {
	return { fits: bytes <= FREE_CEILING, headroom: FREE_CEILING - bytes };
}

function arg(name: string, fallback?: string): string | undefined {
	const hit = process.argv.find((a: string) => a.startsWith(`--${name}=`));
	return hit ? hit.slice(name.length + 3) : fallback;
}

const has = (name: string) => process.argv.includes(`--${name}`);

/** the tarball name a hydrate resolves by convention, so neither side needs an index */
export function payloadName(release: string): string {
	return `drupflare-worker-${release}.tar.gz`;
}

function gitCommit(root: string): string {
	try {
		return execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
	} catch {
		return 'unknown';
	}
}

/** Dry-runs the canonical config and prices the bundle. Needs no credential; measured, not assumed. */
function checkBundle(root: string): number {
	const outdir = join(root, 'dist/dry-run');
	// a stale artifact in the outdir is counted by measureBundle: a leftover 11 MB probe wasm read
	// 6,542,971 against a real 2,876,078
	rmSync(outdir, { recursive: true, force: true });
	const out = execFileSync(
		'bunx',
		['wrangler', 'deploy', '-c', 'wrangler.jsonc', '--dry-run', '--outdir', outdir],
		{ cwd: root, encoding: 'utf8', maxBuffer: 1 << 28, stdio: ['ignore', 'pipe', 'pipe'] }
	);
	const bytes = parseWranglerGzipBytes(out);
	if (bytes === undefined) {
		throw new Error(`wrangler printed no gzip figure:\n${out}`);
	}
	const { fits, headroom } = ceilingVerdict(bytes);
	const local = measureBundle(outdir);
	console.log(
		`bundle ${bytes} gzipped bytes against ${FREE_CEILING}: ` +
			`${fits ? `fits, ${headroom} under` : `OVER by ${-headroom}`} ` +
			`(local instrument reads ${local.gz})`
	);
	if (!fits) throw new Error('the bundle does not fit the free plan ceiling');
	return bytes;
}

if (import.meta.main) {
	const root = resolve(import.meta.dirname, '..');
	const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
		version?: string;
	};
	const release = arg('version', pkg.version)!;

	if (has('check-bundle')) {
		checkBundle(root);
		process.exit(0);
	}

	const plan = payloadPlan(root);
	const files = expandPlan(root, plan);
	const seeded = scanSeededCredentials(root, files);
	if (seeded.length && !has('allow-seeded-credentials')) {
		console.error('the payload carries credentials that Workers assets serve PUBLICLY:');
		for (const { path, kind } of seeded) console.error(`  ${path}  ${kind}`);
		console.error(
			'\nEvery site deployed from this payload would share them. Strip the rows, rotate on\n' +
				'first boot, or pass --allow-seeded-credentials to publish anyway. See\n' +
				'PUBLISHING.md, "Seeded Credentials".'
		);
		process.exit(1);
	}

	const out = resolve(root, arg('out', 'dist')!);
	mkdirSync(out, { recursive: true });
	const manifest = buildManifest(root, release, gitCommit(root), files, plan.interpreter);
	const manifestPath = join(out, 'manifest.json');
	writeFileSync(manifestPath, JSON.stringify(manifest, null, '\t') + '\n');

	const tarball = join(out, payloadName(release));
	execFileSync('tar', ['-czf', tarball, '-C', out, 'manifest.json', '-C', root, ...files], {
		maxBuffer: 1 << 28
	});
	const digest = sha256(tarball);
	writeFileSync(join(out, 'SHA256SUMS'), `${digest}  ${payloadName(release)}\n`);

	const size = statSync(tarball).size;
	console.log(
		JSON.stringify(
			{
				release,
				files: manifest.totals.files,
				payloadBytes: manifest.totals.bytes,
				tarball: relative(root, tarball),
				tarballBytes: size,
				sha256: digest,
				seededCredentials: seeded.length
			},
			null,
			2
		)
	);
	const sums = relative(root, join(out, 'SHA256SUMS'));
	console.log(
		'\nattach it to a draft release, which is what the Release Project workflow verifies:\n' +
			`  gh release create v${release} --draft --title "drupflare/worker v${release}" --notes pending\n` +
			`  gh release upload v${release} ${relative(root, tarball)} ${sums} --clobber`
	);
}
