/**
 * Removes shipped secrets from the per-file Drupal pack.
 *
 * ```sh
 * bun scripts/scrub-pack-secrets.ts            # scrub in place
 * bun scripts/scrub-pack-secrets.ts --check    # report only, exit 1 if a secret is present
 * ```
 *
 * `assets/drupal-pf/core.pf.bin` is served publicly by Workers assets, and it carried
 * `settings.php` with a real `$settings['hash_salt']` -- one value, identical on every site
 * deployed from the payload, fetchable by anyone. That salt signs one-time login links and form
 * tokens, so holding the payload was enough to mint a valid password-reset URL for any site.
 *
 * The salt is blanked rather than deleted. `Settings::getHashSalt()` throws on an empty value, so a
 * site whose host override failed to run stops with `Missing $settings['hash_salt']` instead of
 * quietly falling back to a public one.
 *
 * IN PLACE, at the same offsets. The pack is an index of `{p, o, c, l}` into one blob, so rewriting
 * the whole file would move 11,444 offsets to change one. The rewritten entry is deflated back into
 * its own slot and the unused tail is zero-filled; a longer result is appended and the old slot
 * zeroed. Either way no byte of the old secret survives, which appending alone would not achieve.
 *
 * @see src/ops/site-secrets.ts for the per-site salt this leaves room for
 * @see scripts/release-payload.ts, whose scanner refuses to publish a payload that still has one
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { deflateRawSync, inflateRawSync } from 'node:zlib';

/**
 * One entry of the per-file index: path, offset, stored length, raw length, mtime.
 *
 * `s` marks a member stored VERBATIM, which `pack-perfile.ts` does whenever deflate would grow the
 * file -- 36 of 11,444 here. Inferring that from `c === l` instead of reading the flag looks
 * equivalent and is not: it is a guess about the format that happens to agree today.
 */
export type PackEntry = { p: string; o: number; c: number; l: number; m?: number; s?: 1 };

/** what a scrub did, so the caller can tell "already clean" from "just fixed" */
export type ScrubResult = {
	path: string;
	found: string[];
	rewritten: boolean;
	/** true when the new blob did not fit its slot and had to move to the end */
	relocated?: boolean;
};

/**
 * The rewrites, keyed by the file they apply to.
 *
 * A regex rather than a literal: the salt is regenerated by whoever builds the Drupal tree, so
 * matching the value would go stale the first time somebody rebuilds the pack and the scrub would
 * silently pass on a file that still has a secret.
 */
export const SECRET_REWRITES: readonly {
	file: string;
	kind: string;
	find: RegExp;
	replace: string;
}[] = [
	{
		file: 'sites/default/settings.php',
		kind: 'hash_salt',
		// anchored to the start of a line so the documentation example inside the docblock above
		// it -- which assigns from file_get_contents() -- is left alone, and requiring a NON-EMPTY
		// literal is what makes the scrub idempotent and `--check` able to pass
		find: /^\$settings\['hash_salt'\] = '[^']+';$/m,
		replace:
			'// minted per site by the Durable Object and appended below; empty here so a missing\n' +
			'// override throws instead of sharing one salt across every deployed site\n' +
			"$settings['hash_salt'] = '';"
	}
];

/** Reads the index and blob of a per-file pack. */
export function readPack(dir: string): { index: Record<string, PackEntry>; bin: Uint8Array } {
	const index = JSON.parse(readFileSync(join(dir, 'core.pf.json'), 'utf8')) as Record<
		string,
		PackEntry
	>;
	return { index, bin: new Uint8Array(readFileSync(join(dir, 'core.pf.bin'))) };
}

/** @returns the decompressed bytes of one entry, honouring the stored-verbatim flag */
export function readEntry(bin: Uint8Array, entry: PackEntry): Uint8Array {
	const slice = bin.subarray(entry.o, entry.o + entry.c);
	return entry.s === 1 ? slice : new Uint8Array(inflateRawSync(slice));
}

/** latin1 keeps every byte addressable, so a binary member cannot throw the way a UTF-8 decode can */
export function decodeLatin1(bytes: Uint8Array): string {
	return new TextDecoder('latin1').decode(bytes);
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
	if (a.length !== b.length) return false;
	for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
	return true;
}

/**
 * Applies every rewrite whose file is present.
 *
 * @param check - report what would change without writing
 */
export function scrubPack(dir: string, check = false): ScrubResult[] {
	const { index, bin } = readPack(dir);
	// the offsets as they were, so the verification below compares against the pack on disk rather
	// than against the index it is in the middle of mutating
	const original: Record<string, PackEntry> = JSON.parse(JSON.stringify(index));
	const byPath = new Map<string, string>();
	for (const [key, entry] of Object.entries(index)) byPath.set(entry.p, key);

	const results: ScrubResult[] = [];
	// a COPY: the rewrite mutates in place, and verifying a mutated buffer against itself is the
	// shared-instrument mistake -- it would compare the new bytes to the new bytes and always pass
	let blob = new Uint8Array(bin);
	let dirty = false;

	for (const rule of SECRET_REWRITES) {
		const key = byPath.get(rule.file);
		if (key === undefined) continue;
		const entry = index[key]!;
		const before = new TextDecoder().decode(readEntry(blob, entry));
		if (!rule.find.test(before)) {
			results.push({ path: rule.file, found: [], rewritten: false });
			continue;
		}
		results.push({ path: rule.file, found: [rule.kind], rewritten: !check });
		if (check) continue;

		const after = before.replace(rule.find, rule.replace);
		const raw = new TextEncoder().encode(after);
		const deflated = new Uint8Array(deflateRawSync(raw, { level: 9 }));
		// same rule pack-perfile.ts applies: store verbatim when deflate would not shrink it
		const verbatim = deflated.length >= raw.length;
		const packed = verbatim ? raw : deflated;
		if (verbatim) entry.s = 1;
		else delete entry.s;
		if (packed.length <= entry.c) {
			// the old slot is overwritten and its tail zeroed: leaving the original bytes in place
			// would leave the secret readable at the offset the index no longer points at
			blob.set(packed, entry.o);
			blob.fill(0, entry.o + packed.length, entry.o + entry.c);
		} else {
			blob.fill(0, entry.o, entry.o + entry.c);
			const grown = new Uint8Array(blob.length + packed.length);
			grown.set(blob, 0);
			grown.set(packed, blob.length);
			results[results.length - 1]!.relocated = true;
			entry.o = blob.length;
			blob = grown;
		}
		entry.c = packed.length;
		entry.l = raw.length;
		dirty = true;
	}

	if (dirty) {
		// every OTHER entry must still inflate to exactly what it did before, because a wrong
		// offset would present as a missing file at boot rather than as a failure here
		verifyUntouched(bin, blob, index, original);
		writeFileSync(join(dir, 'core.pf.bin'), blob);
		writeFileSync(join(dir, 'core.pf.json'), JSON.stringify(index));
	}
	return results;
}

/** Throws unless every entry not named in {@link SECRET_REWRITES} inflates to its original bytes. */
function verifyUntouched(
	before: Uint8Array,
	after: Uint8Array,
	index: Record<string, PackEntry>,
	original: Record<string, PackEntry>
): void {
	const rewritten = new Set(SECRET_REWRITES.map((r) => r.file));
	for (const [key, entry] of Object.entries(index)) {
		if (rewritten.has(entry.p)) continue;
		const a = readEntry(before, original[key]!);
		const b = readEntry(after, entry);
		if (!bytesEqual(a, b))
			throw new Error(`scrub moved ${entry.p}; refusing to write the pack`);
	}
}

if (import.meta.main) {
	const dir =
		process.argv.find((a: string) => !a.startsWith('--') && a.includes('drupal-pf')) ??
		'assets/drupal-pf';
	const check = process.argv.includes('--check');
	if (!existsSync(join(dir, 'core.pf.json'))) {
		console.error(`no per-file pack at ${dir}; run bun run assets:pack first`);
		process.exit(2);
	}
	const results = scrubPack(dir, check);
	let bad = 0;
	for (const r of results) {
		if (r.found.length === 0) {
			console.log(`${r.path}  clean`);
			continue;
		}
		bad++;
		const how = r.rewritten ? (r.relocated ? 'rewritten (relocated)' : 'rewritten') : 'PRESENT';
		console.log(`${r.path}  ${r.found.join(', ')}  ${how}`);
	}
	if (check && bad) {
		console.error('\nthe pack still ships a secret; run bun run assets:scrub');
		process.exit(1);
	}
}
