/**
 * The driver digest the packed `cache_container` row was baked with. GENERATED by
 * `bun run assets:container`; empty until a bake records one.
 */
export const PACKED_CONTAINER_DIGEST: string = '9cbc5c32c89c1f3a';
