/**
 * The opcache file cache the pack ships. GENERATED by `scripts/bake-opcache.ts`; null when none was
 * baked, in which case the `pack` arm mounts nothing and compiles as `off` would.
 *
 * `systemId` is the directory opcache keys the cache by. It is derived from the interpreter build, so
 * a cache baked on another binary is never read, and the mount has to know it to link `/tmp` to it.
 * `source` is `opcacheSourceKey()` at bake time; the mount skips a cache compiled from other sources.
 */
export const OPCACHE_PACK: {
	systemId: string;
	files: number;
	bytes: number;
	source: string;
} | null = null;
