/**
 * What this site ships, from `drupal-src/composer.lock`. GENERATED -- run
 * `bun run gen:lock` after any composer change; `tests/node/shipped-lock.spec.ts` fails on drift.
 */
export const SHIPPED_LOCK_VERSIONS: Record<string, string> = {
	'asm89/stack-cors': 'v2.4.0',
	'composer/installers': 'v2.3.0',
	'composer/semver': '3.4.4',
	'doctrine/lexer': '3.0.1',
	'drupal/admin_toolbar': '3.6.3',
	'drupal/core': '11.4.5',
	'drupal/core-composer-scaffold': '11.4.5',
	'drupal/core-project-message': '11.4.5',
	'drupal/core-recipe-unpack': '11.4.5',
	'drupal/core-recommended': '11.4.5',
	'drupal/core-vendor-hardening': '11.4.5',
	'drupal/ctools': '4.1.1',
	'drupal/pathauto': '1.15.0',
	'drupal/token': '1.17.0',
	'egulias/email-validator': '4.0.4',
	'guzzlehttp/guzzle': '7.15.3',
	'guzzlehttp/promises': '2.5.2',
	'guzzlehttp/psr7': '2.13.0',
	'justinrainbow/json-schema': '6.8.2',
	'marc-mabe/php-enum': 'v4.7.2',
	'masterminds/html5': '2.10.1',
	'mck89/peast': 'v1.17.7',
	'pear/archive_tar': '1.6.1',
	'pear/console_getopt': 'v1.4.3',
	'pear/pear-core-minimal': 'v1.10.18',
	'pear/pear_exception': 'v1.0.2',
	'php-tuf/composer-stager': 'v2.1.1',
	'psr/container': '2.0.2',
	'psr/event-dispatcher': '1.0.0',
	'psr/http-client': '1.0.3',
	'psr/http-factory': '1.1.0',
	'psr/http-message': '2.0',
	'psr/log': '3.0.2',
	'ralouphie/getallheaders': '3.0.3',
	'revolt/event-loop': 'v1.0.9',
	'sebastian/diff': '7.0.0',
	'symfony/console': 'v7.4.17',
	'symfony/dependency-injection': 'v7.4.17',
	'symfony/deprecation-contracts': 'v3.7.1',
	'symfony/error-handler': 'v7.4.17',
	'symfony/event-dispatcher': 'v7.4.17',
	'symfony/event-dispatcher-contracts': 'v3.7.1',
	'symfony/filesystem': 'v7.4.17',
	'symfony/finder': 'v7.4.17',
	'symfony/http-foundation': 'v7.4.17',
	'symfony/http-kernel': 'v7.4.17',
	'symfony/mailer': 'v7.4.17',
	'symfony/mime': 'v7.4.17',
	'symfony/polyfill-ctype': 'v1.37.0',
	'symfony/polyfill-iconv': 'v1.37.0',
	'symfony/polyfill-intl-grapheme': 'v1.41.0',
	'symfony/polyfill-intl-idn': 'v1.38.1',
	'symfony/polyfill-intl-normalizer': 'v1.38.0',
	'symfony/polyfill-mbstring': 'v1.38.2',
	'symfony/polyfill-php80': 'v1.37.0',
	'symfony/polyfill-php83': 'v1.41.0',
	'symfony/polyfill-php84': 'v1.38.1',
	'symfony/polyfill-php85': 'v1.41.0',
	'symfony/polyfill-php86': 'v1.41.0',
	'symfony/process': 'v7.4.17',
	'symfony/psr-http-message-bridge': 'v7.4.8',
	'symfony/routing': 'v7.4.17',
	'symfony/runtime': 'v7.4.14',
	'symfony/serializer': 'v7.4.17',
	'symfony/service-contracts': 'v3.7.1',
	'symfony/string': 'v7.4.15',
	'symfony/translation-contracts': 'v3.7.1',
	'symfony/validator': 'v7.4.17',
	'symfony/var-dumper': 'v7.4.17',
	'symfony/var-exporter': 'v7.4.16',
	'symfony/yaml': 'v7.4.17',
	'twig/html-extra': 'v3.28.0',
	'twig/twig': 'v3.28.0'
};

/** the Drupal core version these packages were locked against */
export const SHIPPED_CORE_VERSION = '11.4.5';
