import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { XMLWRITER_FIX } from '../../src/drupal/xmlwriter-fix';

/**
 * The pure-PHP `XMLWriter` against the real extension, byte for byte.
 *
 * THE ORACLE IS THE POINT. A polyfill asserted against hand-written expectations only proves it
 * matches what its author imagined; libxml's actual output has behaviour nobody would guess -- an
 * element with TEXT keeps its end tag on the same line while an element with element CHILDREN does
 * not, and `writeElement($n, null)` collapses to `<n/>` where `writeElement($n, '')` does not. Both
 * were found by running this, not by reading the docs.
 *
 * The fragment declares `class XMLWriter` only when the name is free, so on a build WITH the
 * extension it never binds -- which is correct in production and useless for a comparison. The
 * harness renames the class so both implementations exist at once and one script drives each.
 *
 * `node` lane because it needs a real PHP binary. Skips with a printed reason when that PHP has no
 * ext-xmlwriter, since then there is no oracle rather than a defect.
 */

const dir = mkdtempSync(join(tmpdir(), 'cfw-xmlwriter-'));

/** the fragment with the class renamed, so it coexists with the real one */
const POLYFILL_AS_PROBE = XMLWRITER_FIX.replace(
	"!class_exists('XMLWriter', false)",
	'true'
).replace('class XMLWriter {', 'class CfwXmlWriterProbe {');

function phpHasXmlWriter(): boolean {
	try {
		return (
			execFileSync('php', ['-r', 'echo extension_loaded("xmlwriter") ? "1" : "0";'], {
				encoding: 'utf8'
			}).trim() === '1'
		);
	} catch {
		return false;
	}
}

/**
 * Runs one body against both implementations and returns what each produced.
 *
 * The body is written once with `%W%` standing in for the class name, so there is exactly one
 * source of truth for the calls being compared -- two near-identical scripts would let a typo make
 * the comparison pass by testing different things.
 */
function bothWays(body: string): { real: string; poly: string } {
	const run = (className: string, prelude: string): string => {
		const file = join(dir, `run-${className}.php`);
		writeFileSync(
			file,
			`<?php\n${prelude}\n$w = new ${className}();\n${body.replace(/%W%/g, '$w')}\necho $out;\n`
		);
		return execFileSync('php', [file], { encoding: 'utf8' });
	};
	return {
		real: run('XMLWriter', ''),
		poly: run('CfwXmlWriterProbe', POLYFILL_AS_PROBE)
	};
}

describe('the pure-PHP XMLWriter matches libxml', () => {
	const oracle = phpHasXmlWriter();

	/**
	 * The whole sitemap shape, which is what the polyfill exists for.
	 *
	 * Every call `simple_sitemap` 4.2.1 makes is in here: the eleven inventoried methods driven in
	 * the order `SitemapGeneratorBase::generate()` drives them.
	 */
	it('produces an identical urlset, indentation and all', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->setIndent(TRUE);
%W%->startDocument('1.0', 'UTF-8');
%W%->writePI('xml-stylesheet', 'type="text/xsl" href="/sitemap.xsl"');
%W%->writeComment('Generated by the Simple XML Sitemap Drupal module.');
%W%->startElement('urlset');
%W%->writeAttribute('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9');
%W%->startElement('url');
%W%->writeElement('loc', 'https://example.com/node/1');
%W%->writeElement('lastmod', '2026-08-23T00:00:00+00:00');
%W%->endElement();
%W%->startElement('url');
%W%->writeElement('loc', 'https://example.com/node/2');
%W%->endElement();
%W%->endElement();
%W%->endDocument();
$out = %W%->outputMemory();`);
		expect(poly).toBe(real);
		// and it is a real document rather than two empty strings agreeing
		expect(real).toContain('<urlset');
		expect(real).toContain('sitemap.xsl');
	});

	/**
	 * The sitemap INDEX, the other document the module writes.
	 */
	it('produces an identical sitemapindex', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->setIndent(TRUE);
%W%->startDocument('1.0', 'UTF-8');
%W%->startElement('sitemapindex');
%W%->writeAttribute('xmlns', 'http://www.sitemaps.org/schemas/sitemap/0.9');
%W%->startElement('sitemap');
%W%->writeElement('loc', 'https://example.com/sitemap.xml?page=1');
%W%->writeElement('lastmod', '2026-08-23T00:00:00+00:00');
%W%->endElement();
%W%->endElement();
%W%->endDocument();
$out = %W%->outputMemory();`);
		expect(poly).toBe(real);
	});

	/**
	 * Escaping, which is where a hand-rolled writer produces invalid XML that still looks fine.
	 *
	 * A `&` in a URL is the common case and an unescaped one makes the whole sitemap unparseable,
	 * so a consumer rejects every URL in it rather than the one that was wrong.
	 */
	it('escapes text and attributes the same way', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->startElement('r');
%W%->writeAttribute('a', 'x & y <z> "q" \\'p\\'');
%W%->writeElement('t', 'a & b < c > d "e" \\'f\\'');
%W%->endElement();
$out = %W%->outputMemory();`);
		expect(poly).toBe(real);
		expect(real).toContain('&amp;');
	});

	/**
	 * NULL and empty string are different documents, which is the kind of thing only an oracle
	 * catches: one collapses to a self-closing tag and the other does not.
	 */
	it('distinguishes a null child from an empty one', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->startElement('r');
%W%->writeElement('empty', '');
%W%->writeElement('nothing');
%W%->startElement('collapsed');
%W%->endElement();
$out = %W%->outputMemory();`);
		expect(poly).toBe(real);
		expect(real).toContain('<nothing/>');
		expect(real).toContain('<empty></empty>');
	});

	/**
	 * Indentation off, which is what a production sitemap actually ships with when bytes matter.
	 */
	it('matches with indentation disabled', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->setIndent(FALSE);
%W%->startDocument('1.0', 'UTF-8');
%W%->startElement('urlset');
%W%->startElement('url');
%W%->writeElement('loc', 'https://example.com/');
%W%->endElement();
%W%->endElement();
%W%->endDocument();
$out = %W%->outputMemory();`);
		expect(poly).toBe(real);
		expect(real).not.toContain('\n <url>');
	});

	/**
	 * outputMemory(TRUE) FLUSHES, which is what makes a chunked generator work: simple_sitemap calls
	 * it per chunk and would otherwise repeat every previous chunk in each one.
	 */
	it('flushes the buffer on outputMemory, so a second read is empty', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->writeElement('a', '1');
$first = %W%->outputMemory();
$second = %W%->outputMemory();
$out = $first . '|' . $second . '|';`);
		expect(poly).toBe(real);
		expect(real).toBe('<a>1</a>||');
	});

	/**
	 * A deep tree, so the indent DEPTH is compared rather than just its presence.
	 */
	it('indents nested levels identically', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->setIndent(TRUE);
%W%->startElement('a');
%W%->startElement('b');
%W%->startElement('c');
%W%->writeElement('d', 'deep');
%W%->endElement();
%W%->endElement();
%W%->endElement();
$out = %W%->outputMemory();`);
		expect(poly).toBe(real);
	});

	/**
	 * An attribute written after a child is a caller error, and libxml has a definite answer for it.
	 * Matching the answer matters more than the answer being sensible.
	 */
	it('agrees on an attribute written too late', () => {
		if (!oracle) return;
		const { real, poly } = bothWays(`
%W%->openMemory();
%W%->startElement('r');
%W%->writeElement('child', 'x');
$late = %W%->writeAttribute('a', 'b') ? 'true' : 'false';
%W%->endElement();
$out = %W%->outputMemory() . '|' . $late;`);
		expect(poly).toBe(real);
	});
});
